### ISSUE TITLE
Foreign plural ending ignores foreign-format

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/acro#149]
**[Original report](https://bitbucket.org/cgnieder/acro/issue/149) by Anonymous.**

----------------------------------------

When using `\acp` for the first occurrence of an acronym which uses a `foreign` form and uses `foreign-format` the plural ending appended to the `foreign` form doesn't use the `foreign-format`.

MWE:

```tex
\documentclass[]{article}

\usepackage[british, ngerman]{babel}
\usepackage{acro}

\acsetup
  {%
    ,foreign-format=\itshape
    ,list-foreign-format=\mylistforeignformat
  }

\DeclareAcronym{svm}
  {%
    ,short=SVM
    ,long=Stützvektormaschine
    ,long-plural=n
    ,foreign=Support Vector Machine
    ,foreign-lang=british
  }

\begin{document}
\acp{svm} \ac{svm}
\end{document}
```

**Comment by Skillmon** [comment]
Thank you very much for the fix to a bug I didn't even discover as I was missing the `format-include-endings` option!

**Comment by cgnieder** [comment]
I see you've found the new home of `acro` :)
