### ISSUE TITLE
list-caps issue on acro v2.11d

### ISSUE THREAD

**Issue by KiprasR** [cgnieder/acro#152]
LaTeX code fails to compile if `list-caps` set to `true` and the acronym begins with a non-letter:

```latex
\documentclass{scrreprt}
\usepackage{classicthesis} 
\usepackage{hyphenat}
\usepackage[euler]{textgreek}
\usepackage[version=4]{mhchem} 
\usepackage[list-caps=true]{acro}

\DeclareAcronym{BBO}{
	short=BBO,
	long=\textbeta\hyp{}barium borate,
	extra=($\ce{\text{\textbeta\hyp{}}BaB2O4}$),
	sort=beta-barium borate
}

\begin{document}
\printacronyms
\ac{BBO} is a popular nonlinear crystal.
\end{document}
```

Everything works fine if `list-caps=true` is omitted. This used to be not an issue on older versions of `acro`.

**Comment by cgnieder** [comment]
Looks like `\textbeta` is not robust. I'd simply use `\chembeta` in this case. In the example below I modified a few other things, too (not related to the issue). For example `acro` discourages the use of setting options as package options:

> They might work as package options to \usepackage as well but I do not recommend it and will likely remove this in a future version 3 of `acro`.

Also, the parentheses around the extra-text could/should be added via option instead of manually, IMHO.

```latex
\documentclass{scrreprt}

\usepackage{classicthesis} 
\usepackage[version=4]{mhchem}
\usepackage[euler]{textgreek}

\usepackage{acro}
\acsetup{
  list-caps = true ,
  extra-style = paren
}

\DeclareAcronym{BBO}{
  short = BBO ,
  long  = \chembeta-barium borate ,
  extra = \ce{\beta-BaB2O4} ,
  sort  = beta-barium borate
}

\begin{document}

\printacronyms
\ac{BBO} is a popular nonlinear crystal.

\end{document}
```
![image](https://user-images.githubusercontent.com/2248538/77103105-2cb56200-6a1a-11ea-982d-b19a6abf009b.png)

**Comment by KiprasR** [comment]
OK, this seems viable. I've noticed that `$\text{\textbeta}$` seems to work as well.

As far as other things are concerned:

1.  I'm not using the `extra-style = paren` option, as I have a mix of extras that either need or do not need parentheses in their extended desciption (it's just easier to add them manually for the ones that need them). 
2. I prefer to use `\hyp{}` instead of `-`, as it allow LaTeX to perform a line break on the hyphen symbol, if the long form of an acronym is encountered at the end of the line. Otherwise the long form might protrude over the text margin.

**Comment by cgnieder** [comment]
1. I thought you might :)
 2. I'd prefer a `babel` shortcut but never mind.

I'll close this then.
