### ISSUE TITLE
How to support both version 2 and 3 in a single document?

### ISSUE THREAD

**Issue by johannes-krude** [cgnieder/acro#156]
I am the maintainer of an internal template at our organization which uses and provides defaults fo acro. We have users on different versions of texlive and are now running into the problem of failing to compile documents on texlive-2020 due to acro.

`\usepacke[version=2]{acro}` does not solve our problem since this fails on texlive-2019 which has acro-2.11c.

Is there a better way to support the acro versions from texlive-2020 and texlive-2019 in a single document, then copying a single acro version into our template?

**Comment by cgnieder** [comment]
You can check the value of `\c_acro_version_major_number_tl`. This should be a reliable test.

```latex
\documentclass{article}
\usepackage{acro}

\begin{document}

\ExplSyntaxOn
\int_compare:nTF { \c_acro_version_major_number_tl = 3}
  {version~ 3}
  {not~ version~ 3}
\ExplSyntaxOff

\ifnum\numexpr\csname c_acro_version_major_number_tl\endcsname=3\relax
  version 3%
\else
  not version 3%
\fi

\end{document}
```

**Comment by johannes-krude** [comment]
But then I have to have two versions of my document and select which one to use depending on the acro version. Is there a way, where I don't have to do everything twice for two different acro versions?

**Comment by cgnieder** [comment]
I don't understand. One file really suffices, that's the whole purpose of the switch…

```latex
\ifacroversionthree{
  \acsetup{ make-links = true }
}{
  \acsetup{ hyperref = true }
}
```

> where I don't have to do everything twice for two different acro versions?

Not everything, of course, but you probably cannot avoid some duplication. Can you show me an example code that is causing you trouble? Maybe I can make some suggestions…

----
PS: You said *document*? Aren't you maintaining some sort of package which hides the necessary code from the user?

**Comment by johannes-krude** [comment]
I can show you two examples which do not work anymore in acro-3:
```
\DeclareAcronym{LP}{long=Logical Process,short-indefinite=an,long-plural=es}
```
and
```
`\ProvideAcroEnding{possessive}{'s}{'s}
\ProvideAcroEnding{possessiveplural}{s'}{s'}

\ExplSyntaxOn
\NewAcroCommand \acg
  {
    \acro_possessive:
    \acro_use:n {#1}
  }
\NewAcroCommand \acsg
  {
    \acro_possessive:
    \acro_short:n {#1}
  }
\NewAcroCommand \aclg
  {
    \acro_possessive:
    \acro_long:n {#1}
  }
\NewAcroCommand \acgp
  {
    \acro_possessiveplural:
    \acro_use:n {#1}
  }
\NewAcroCommand \acsgp
  {
    \acro_possessiveplural:
    \acro_short:n {#1}
  }
\NewAcroCommand \aclgp
  {
    \acro_possessiveplural:
    \acro_long:n {#1}
  }
\ExplSyntaxOff
```

So it seems to me, that everything acro related now has to be implemented twice within such a switch statement.

Do you still maintain the [version=2] variant of acro or does this give the same result as me copying the last acro-2 version into my package? I could build something which detects whether the [version=2] argument is necessary and then remember this in the aux file and restart compilation. But this only brings an advandage if you still maintain the [version=2] variant.

**Comment by cgnieder** [comment]
`version=2` just loads a copy of the release before version 3. That is it *does* give the same result as you copying the last version. I will leave in `acro` for at least a year.

Not giving the `short` form always produced a warning (and in early versions an error) and was never encouraged. Version 3 now explicitly allows it if you say

```latex
\acsetup{use-id-as-short=true}
```

The file below compiles with version 2 and version3:

```latex
\documentclass{article}
\usepackage{acro}

\newcommand\ifacrothree{%
  \ifnum\numexpr\csname c_acro_version_major_number_tl\endcsname=3\relax
}

\ifacrothree
  \acsetup{use-id-as-short}
  \def\ProvideAcroEnding{\DeclareAcroEnding}
\fi

\ProvideAcroEnding{possessive}{'s}{'s}
\ProvideAcroEnding{possessiveplural}{s'}{s'}

\ifacrothree
  \NewAcroCommand\acg{m}{%
    \acropossessive
    \UseAcroTemplate{first}{#1}%
  }
\else
\ExplSyntaxOn
  \NewAcroCommand \acg {
    \acro_possessive:
    \acro_use:n {#1}
  }
\ExplSyntaxOff
\fi


\DeclareAcronym{LP}{
  long=Logical Process,
  short-indefinite=an,
  long-plural=es
}

\begin{document}

1: \ac{LP} \par
2: \iac{LP} \par
3: \acg{LP} \par
4: \aclp{LP}

\end{document}
```

**Comment by johannes-krude** [comment]
Thanks a lot. This helped me to port our arco setup to work with acro-3 and acro-2. When ubuntu-20.04 is no longer supported in 2025 I can then finally remove the acro-2 setup code.

**Comment by cgnieder** [comment]
I can keep the version 2 file in acro until then if you like. 




Clemens Niederberger


https://github.com/cgnieder







On Thu, May 7, 2020 at 2:16 PM +0200, "johannes-krude" <notifications@github.com> wrote:















Thanks a lot. This helped me to port our arco setup to work with acro-3 and acro-2. When ubuntu-20.04 is no longer supported in 2025 I can then finally remove the acro-2 setup code.
