### ISSUE TITLE
Error with format property and babel

### ISSUE THREAD

**Issue by callegar** [cgnieder/acro#157]
Hi, trying to compile a document that uses `foreing-lang` (or `foreing-babel` according to the new option name), I am now getting an error:
```
 ! Undefined control sequence.
\bbl@fixname #1->\begingroup \def \bbl@tempe 
                                             {l@}\edef \bbl@tempd {\noexpand...
```
where the acronym is first used.
This is in a large old document I have. In case the issue is not a trivial one, I can try to distill a small test case.

**Comment by cgnieder** [comment]
I have no problems with this file:

```latex
\documentclass{article}
\usepackage[ngerman,main=british]{babel}
\usepackage{acro}

\DeclareAcronym{test}{
  short = short ,
  long = description ,
  foreign = bla bla ,
  foreign-babel = ngerman
}

\begin{document}

\ac{test}

\end{document}
```

**Comment by callegar** [comment]
I was fearing that... I'll try to look into the matter and create a test case, then.

**Comment by cgnieder** [comment]
Don't get me wrong but you *always* need to pin down where the cause of an error is. All the more if you want to report an issue. The developers needs to be able to recreate the problem in order to fix it. This is why we (almost) *always* want to see a [MWE](https://tex.meta.stackexchange.com/questions/228/).

**Comment by callegar** [comment]
I understand you perfectly... I also have a couple of latex packages (nowhere near the sophistication of acro). Was trying to cut a corner, because at times when something is completely renewed some typos may happen and I was hoping for something like that.

So here we go. The issue is actually with the `format` property, and was triggered in my code because I was using `foreign-format`.  Using `babel` is needed to trigger the issue. Apparently, you cannot set `format=\emph`, which was OK in `acro` version 2. Interestingly, you can set `format=\textit`, which is not exactly the same though.

See the following:
```latex
\documentclass{article}
\usepackage{acro}
\usepackage[italian]{babel}

\acsetup{format=\emph}

\DeclareAcronym{MOS}{
  short = MOS,
  long = metallo-ossido-semiconduttore,
  }

\begin{document}
  
This is an acronym test \ac{MOS}
  
\end{document}
```

**Comment by cgnieder** [comment]
Oh, yes, that. I've discovered it a few days ago and already fixed it for the upcoming release.
Meanwhile use `\acsetup{format=\em}`.

Thanks for reporting, anyway.

**Comment by callegar** [comment]
Great, thanks. Is there a version committed on github to build and test already?

**Comment by cgnieder** [comment]
Yes: https://github.com/cgnieder/acro/commit/1d11ad66fd3719b64e4141b9b1e332181443af0e

**Comment by callegar** [comment]
Thanks, works fine here!!!
