### ISSUE TITLE
longtable template uses longtabu

### ISSUE THREAD

**Issue by u-fischer** [cgnieder/acro#158]
in acro.sty line 4988 following I see 

      \NewAcroTemplate[list] {longtable}

and it contains \begin{longtabu}. Not tested, but it looks wrong.

Side-remark: in view of the unmaintained and broken status of tabu (https://github.com/tabu-issues-for-future-maintainer/tabu) I would either remove the longtabu template or at least add a warning in the documentation.

**Comment by cgnieder** [comment]
Thanks for reporting. I already noticed and fixed it for the next release (probably this weekend).

I am aware of the status of `tabu` but you're probably right, I'll add a note in the manual.
