### ISSUE TITLE
Missing rerun boolean

### ISSUE THREAD

**Issue by pneureuther** [cgnieder/acro#159]
I was using `acro` for my phd thesis. Since the `acro` update to version 3.x I switched to `acro2` because I use a self defined list style and I am currently lacking the time to update it.

When using `acro2` I get the following errors at compilation:

`! Undefined control sequence. <argument> \g__acro_rerun_bool `

`! Missing number, treated as zero. \acro@rerun@check`

These errors do not prevent `acro` to work. In order to understand these errors I compared the old `acro.sty` (of version 2.x) and `acro2.sty`. From this comparison I saw that line

`\bool_new:N      \g__acro_rerun_bool`

is missing in `acro2.sty`. After adding this code line in my local LaTeX installation, both errors vanished and `acro2` is nicely working.

Could you please correct this error. Thank you very much for maintaining `acro`.

**Comment by cgnieder** [comment]
Do I understand correctly that you are using `\usepackage{acro2}`?

If yes: this is *not supposed to work*. The recommended (and tested) usage is:

```latex
\usepackage[version=2]{acro}
```

**Comment by pneureuther** [comment]
First of all, thank your for your super fast respons.

As you suspected, I used `\RequirePackage{acro2}`  in my class file and received the described error. When I was scanning the manual for a solution regarding my old list style from version 2, I unfortunately missed the the new version option. With the suggested solution `\RequirePackage[version=2]{acro}` everything works fine.
