### ISSUE TITLE
Citation needed for German ortography claim regarding omitting a space in activate-trailing-tokens in manual

### ISSUE THREAD

**Issue by rugk** [cgnieder/acro#165]
In acro v2.10c page 27 of the manual, you write this:

> Let’s say you’re a German chemist and you have [Polyurethan]
> and you use it the first time like this:
> `\ac{PU}-Hartschaum`
> then according to German orthography and typesetting rules this should be printed as
>  > “Polyurethan(PU)-Hartschaum”
>
> i. e., with _no_ space between long and short form.

It suggest to use `activate-trailing-tokens = {dash,babel-hyphen},` to achieve this.

I've tried to find a source/reference/proof for this, but could not find one so far.
Also, it would be better if that would have been included in the PDF manual, because that is a clear claim [that needs citation](https://xkcd.com/285/).

So do you have a reference for that?

**Comment by rugk** [comment]
Any comment @cgnieder or shall I ask on Stackexchange somewhere (maybe "German language SE"?) hehe :wink:

**Comment by rugk** [comment]
> or shall I ask on Stackexchange somewhere (maybe "German language SE"?)

Well – [did that now](https://german.stackexchange.com/q/60550/19278)… :thinking:

**Comment by cgnieder** [comment]
Maybe this one:

https://www.duden.de/sprachwissen/sprachratgeber/Klammern-und-Bindestrich

I think, this is where I verified the claim.

Best,

Clemens Niederberger
https://github.com/cgnieder

________________________________

**Comment by rugk** [comment]
Oh thanks. I've added that to the SE question.

**Comment by cgnieder** [comment]
I'll close this for now. We can reopen it if new information is found.
