### ISSUE TITLE
\acuse failing

### ISSUE THREAD

**Issue by G-Flavio** [cgnieder/acro#166]
The command \acuse is failing when the list contains more than one acronym 

The MWE
```
\documentclass{book}
\usepackage{acro} 

\DeclareAcronym{CFD}
{
	short = CFD,
	long  = Computational Fluid Dynamics 
} 
\DeclareAcronym{FMM}
{
	short = FMM,
	long  = Fast Multipole Method 
}

\begin{document}
\acuse{CFD,FMM}
\printacronyms
\end{document}
```

The error:

> ! You can't use `\relax' after \advance.
> <argument> \g__acro_CFD,FMM_int 
>                                 
> l.16 \acuse{CFD,FMM}
>                     
> I'm forgetting what you said and not changing anything.
> 
> ! Missing $ inserted.
> <inserted text> 
>                 $
> l.16 \acuse{CFD,FMM}
>                     
> I've inserted a begin-math/end-math symbol since I think
> you left one out. Proceed, with fingers crossed.

Miktek version 20.6.29 
OS Windows 

I could not test it in any other setup so I am not sure the error is reproducible

**Comment by cgnieder** [comment]
Thanks. That is a bug (or a wrongly documented function) -- this is supposed to work. You can use this for the time being:

```latex
\documentclass{article}
\usepackage{acro}

\DeclareAcronym{a}{
  short = a ,
  long  = the letter a
}
\DeclareAcronym{b}{
  short = b ,
  long  = the letter b
}

\acsetup{
  single=true,
  list/display=all,
  pages/display=all
}

\ExplSyntaxOn
\RenewDocumentCommand \acuse {m}
  { \clist_map_function:nN {#1} \acro_use:n }
\ExplSyntaxOff

\begin{document}

\acuse{a,b}

text

\end{document}
```
