### ISSUE TITLE
Migration from v2 acronyms to v3 acronyms?

### ISSUE THREAD

**Issue by rugk** [cgnieder/acro#167]
Maybe I miss something, but is there some kind of migration script from v2 to v3?

Does not have to be included in acro itself, a simple shell or Python script could probably also help.

---

Cross-posted [on Tex Stackexchange](https://tex.stackexchange.com/q/556826/98645).

**Comment by cgnieder** [comment]
There is no such script and frankly I don't think I will find time to write one in the next weeks or even months.

Please feel free to submit one yourself. :)

Clemens Niederberger
https://github.com/cgnieder

________________________________
