### ISSUE TITLE
Doc: 404 links in examples 

### ISSUE THREAD

**Issue by rugk** [cgnieder/acro#168]
The examples taken from Stackoverflow (great idea BTW! :tada: ) 2-6 and 10-12 in the v3.2 doc do have wrong links. They try to link to GitHub, but that results in an error.
(Both the LaTeX files and the pdf as far as I see.)

My tips/ideas:
* either use GitHub permalinks (you can replace `master` in the URL with a tag or commit hash)
* or upload them somewhere that is stable
* or now correct the file names again (back), so it works again…

**Comment by cgnieder** [comment]
I'm sorry but I can't seem to verify this. But I'm not sure I've checked the examples that you mean. You _are_ referring to the examples in appendix A, right? Every link that I've checked worked just fine…

**Comment by rugk** [comment]
Hmm… yeah appendix A, I've even listed the exact numbers.

I use this PDF: https://raw.githubusercontent.com/cgnieder/acro/v3.2/doc/acro-manual.pdf

E.g. the Example 2 has a link to:
* https://raw.githubusercontent.com/cgnieder/acro/v3.2/doc/examples/acro.example.acflike.tex
* and a PDF link to https://raw.githubusercontent.com/cgnieder/acro/v3.2/doc/examples/acro.example.acflike.pdf#[0,{%22name%22:%22Fit%22}]

Both return 404 errors.

**Comment by cgnieder** [comment]
I see. The links are not supposed to work on github but on your tex system. I have texlive 2020 installed and if I open the file with

```console
texdoc acro
```

on my computer then the links work just fine.

**Comment by cgnieder** [comment]
> Hmm… yeah appendix A, I've even listed the exact numbers.
> 
But there is no example 2-6 and no example 10-12? There are examples 1 through 12…

**Comment by rugk** [comment]
Hmm? Of course I mean example 2, 3, 4, …6 with 2-6 (i.e. `[2..6]` in mathematics terms if that helps :upside_down_face:)

And for working on GitHub: Ah, so this is still processed hmm.
But as you can also view that online (on CTAN as well), I guess the GitHub links should work anyway. And some do. Just some others do not…

**Comment by cgnieder** [comment]
Oh, my bad… Anyway, the links are always generated as relative paths to the current path and assume a directory `examples` in the current directory:

```latex
\def\acro@example@texfile@path##1{./examples/acro.example.##1.tex}%
\def\acro@example@pdffile@path{./examples/acro.example}%
```

It never occurred to that some would use github for reading a latex package manual.
(BTW: I configured my browser actually to download PDFs instead of opening them, I need check this on my other computer. Maybe I can reproduce your problems then)

**Comment by rugk** [comment]
Would you like to keep this issue open until then? It's very clearly an issue at least if you read that online on GitHub at least. (Just tried on CTAN and yeah, seems to work there wow.)

**Comment by cgnieder** [comment]
To be honest: this is very low on my list. Links are working on the local computer (where they're supposed to) and even on CTAN (where they weren't).

I believe the problem actually is githubusercontent.com itself and how it fetches content from github. For example https://raw.githubusercontent.com/cgnieder/ also gives a 404 error, as do https://raw.githubusercontent.com/cgnieder/acro/, https://raw.githubusercontent.com/cgnieder/acro/v3.2/, and https://raw.githubusercontent.com/cgnieder/acro/v3.2/doc/

This doesn't look as if I can even do something about it.

**Comment by rugk** [comment]
Yeah, githubusercontent.com only gives you files, no directories. You need the exact link, i.e. just click [the RAW button](https://github.com/cgnieder/acro/blob/master/README) for a file.
