### ISSUE TITLE
Doc: Some acronyms do not backlink to the page they are used

### ISSUE THREAD

**Issue by rugk** [cgnieder/acro#169]
In the v3.2 doc on page 54 your own acronyms list begins.

However, some acronyms like "Polyurethan" or "PNG" do not have a page reference, i.e. it is not stated where they are used. However, they are clearly used, not only in code or examples, but actually printed.
* Polyurethan e.g. on page 29 when you show an example
* PNG on page 14 in the sentence "The acronym PNG is defined as follows" (note this is also correctly linked in the index)

**Comment by cgnieder** [comment]
That's not a bug but a weird combination of options that the manual does for demonstration purposes:

```latex
\documentclass{article}
\usepackage{acro}

\DeclareAcronym{a}{
  short = a ,
  long  = the letter a
}
\DeclareAcronym{b}{
  short = b ,
  long  = the letter b
}

\acsetup{
  single=true,
  list/display=all,
  pages/display=all
}

\begin{document}

\ac{a}

\ac{b}
\ac{b}

\printacronyms

\end{document}
```
