### ISSUE TITLE
Acro v3 fallback fails when using \Acfp

### ISSUE THREAD

**Issue by rugk** [cgnieder/acro#170]
Using the legacy v2 mode with v3.2 of acro (`\usepackage[version=2]{acro}`) to upgrade, I get an error when using `\Acfp{eu}`.

Error:
```
! Undefined control sequence.
\__acro_first_upper_case:n ...t_titlecase_first:n 
                                                  {#1}
l.710 	\Acfp{eu} 
               ist
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

Declaration:

```
\DeclareAcronym{eu}{
	short = EU,
	short-plural = {}, % no plural
	long = {europäische Union},
	long-plural-form = {europäischen Union},
	foreign = {\textit{European Union}},
	foreign-plural = {}, % no plural
	foreign-lang = english
}
```

With v2 this worked fine.

**Comment by cgnieder** [comment]
This looks like you've upgraded `acro` but not the rest of your distribution. The command sequence it refers to is called `\text_titlecase_first:n` and was introduced in the l3kernel 2019-11-20.
Don't update single packages, update your TeX distribution.

**Comment by rugk** [comment]
Uh sry, [people suggested to do that on Tex Stackexchange](https://tex.stackexchange.com/questions/542461/best-practice-to-deal-with-need-for-the-only-for-expanded-acronym#comment1370278_542463).

**Comment by cgnieder** [comment]
Ah, I see. It is not always and not generally a problem to update single packages but it *can* lead to problems in certain circumstances and you've got hit by one :)
