### ISSUE TITLE
Acro V3.2 with "macros" option

### ISSUE THREAD

**Issue by jrast** [cgnieder/acro#173]
I updated the acro package to version 3.2 and now having troubles to compile my document again. According to https://github.com/cgnieder/acro/issues/167 there is no way to automatically migrate a document and I can't find any documentation about the breaking changes between V2.X and V3.2.

Currently I'm struggeling with the following issue: I used the "macros" option in `\acsetup`. It looks like this option has does no longer work? Is there a replacement for this option?

**Comment by jrast** [comment]
I tried to get the functionality back using the following code snippet: 
````latex
\ExplSyntaxOn
\RenewDocumentCommand \DeclareAcronym {m+m}
{ 
   \acro_declare_acronym:nn {#1} {#2}
   \expandafter\newcommand\csname #1\endcsname{\ac{#1}\xspace}
}
\ExplSyntaxOff
```` 
MWE:
````latex
\documentclass{article}
\usepackage{acro}
\usepackage{xparse}
\usepackage{xspace}

\acsetup{
    first-style=footnote,
    list/template=description,
    pages/display=all,
}

\ExplSyntaxOn
\RenewDocumentCommand \DeclareAcronym {m+m}
{ 
   \acro_declare_acronym:nn {#1} {#2}
   \expandafter\newcommand\csname #1\endcsname{\ac{#1}\xspace}
}
\ExplSyntaxOff

\DeclareAcronym{ADC}{
    short=ADC,
    long=Analog Digital Converter
}

\DeclareAcronym{DAC}{
    short=DAC,
    long=Digital Analog Converter
}

\begin{document}
    We are using an \ADC in our system to convert analog signals to digital values.
    Later these values are convterted back to analog signals using a \DAC.
    Therefore \ADC and \DAC are counterparts.
    
    \printacronyms[display=all]

\end{document}
````

**Comment by cgnieder** [comment]
Indeed I dropped the `macros` option. Also the `xspace` option. I never liked them much and as you've shown it is easy to re-implement the behavior.
