### ISSUE TITLE
short-format incorrectly (?) applies to indefinite articles

### ISSUE THREAD

**Issue by hdeyoung** [cgnieder/acro#180]
I would like to use the `short-format` property to print an acronym's short form using small caps. Unfortunately, when I use the `\iac` command, the indefinite article is also included with the format given by `short-format`.

This seems incorrect to me, especially since the plural endings are not affected by `short-format`.  If it is the intended behavior, how can I avoid having the `short-format` applied to indefinite articles?

Here is a minimal example.

    \documentclass{article}

    \usepackage{acro}
    \acsetup{use-id-as-short}

    \DeclareAcronym{LTS}{
      short-indefinite = an,
      short-format = \scshape\MakeLowercase,
      long = labeled transition system,
    }
  
    \begin{document}
    \Iac{LTS} is useful.  Here is \iac{LTS} to use.  \Acp{LTS} are interesting.
    \end{document}

**Comment by cgnieder** [comment]
You are right, the articles should not be formatted. This is now fixed.
