### ISSUE TITLE
\acl sets \acuse

### ISSUE THREAD

**Issue by SamThilmany** [cgnieder/acro#181]
I have noticed that the `\acl` command also sets `\acuse`. I cannot think of a useful usecase of this behaviour and thus am suggesting, to remove the `\acuse` from the `\acs` and `\acl` commands.

Sometimes you want to use the long form of the acronym before you first show that it will be abbreviated in the following document. A good example for this is the abstract. Here, you want to use the long form without defining acronyms as the reader may skip the abstract and will thus never see your definitions. In those cases, you would use `\acl` *before* the first `\ac` call but as `\acl` already sets the `\acused` state, the first `\ac` command will only show the short form of the acronym even though it was never clearly defined.

I could of course call `\acresetall` after the abstract to make sure that the first `\ac` occurence will behave as expected, but I really think this is a fundamental issue that should be fixed.

### MWE

```tex
\documentclass{article}

\usepackage{acro}

\DeclareAcronym{UFO}{
    short = UFO,
    long = unidentified flying object
}

\begin{document}

\acl{UFO}\\
\ac{UFO}

\end{document}
```

Output
```
unidentified flying object
UFO
```

Expected output:
```
unidentified flying object
unidentified flying object (UFO)
```

**Comment by cgnieder** [comment]
This is documented behavior and is true for _any_ of `\ac...` macros. If you don't want that the first use is counted you should use the starred version:
```latex
\begin{document}

\acl*{UFO} \par
\ac{UFO}

\end{document}
```
