### ISSUE TITLE
acro calling an unknown kernel message

### ISSUE THREAD

**Issue by FrankMittelbach** [cgnieder/acro#184]
In the code you find
```
    group         .code:n     =
      \str_case:nnTF {#1}
        { {true} {} {false} {} }
        { \use:c {bool_set_#1:N} \l__acro_cite_group_bool }
        { \msg_error:nnn {kernel} {boolean-values-only} {group} } ,
```
Trouble with this is
 - the documentation indicates that `cite/group` defaults to `cite/group=true`  which is not the case (and in my opinion a pity, i.e., it should be supported)
 - but worse: if you try `cite/group` without a value you get this error message:
```
LaTeX3 Error: Unknown message 'boolean-values-only' for module 
'kernel'.

For immediate help type H <return>.
 ...                                              
```
not nice :-)

**Comment by cgnieder** [comment]
Thanks, fixed. :)
