### ISSUE TITLE
short-format appears to be additive not replacing (as expected)

### ISSUE THREAD

**Issue by FrankMittelbach** [cgnieder/acro#186]
From the documentation (as well as from earlier behavior) I would have expected that one can set a default with `\acsetup` and overwrite that on the individual acronym, but it is seem that both get applied:

```
\documentclass{article}

\usepackage{acro}
\acsetup{short-format=\textbf}

\DeclareAcronym{cd}{short=CD, long=Compact Disc}
\DeclareAcronym{etc}{short = etc.\@, long=et cetera,
                     short-format=\textit, first-style=short}

\begin{document}
\ac{cd}             \\
\ac{etc} --- short format overwrite not honored
\end{document}
```

**Comment by cgnieder** [comment]
This is actually mentioned in the manual (p.19):

> Per default the individual formatting instructions are additive to the global ones. This can be
changed through the option `format/replace` = `true`|`false` (Initial: `false`)

**Comment by FrankMittelbach** [comment]
hmm yes :-)  has this changed recently  (in the last year or so) or have I never noticed that when I made the examples originally?

**Comment by cgnieder** [comment]
It has changed with the upgrade to v3.
I am wondering if the original behavior should be the default, though…

**Comment by FrankMittelbach** [comment]
difficult to say, but if you look around what other packages do then this behavior as a default is fairly unique and normally you can expect that local changes overwrite and not add to the default. would be good for me to know if you alter the default because that affects a lot of the explanation how things work.

**Comment by cgnieder** [comment]
Yes, I decided to revert to the old behavior. It seems to be the more intuitive alternative.
I'll update `acro` this weekend with the new (old) behavior and the bug fixes.
