### ISSUE TITLE
Why is it impossible to set pages on the level of \printacronyms?

### ISSUE THREAD

**Issue by FrankMittelbach** [cgnieder/acro#189]
I know that it is implemented not as list/pages but from a user prespective I would have expected that a could write
```
\printacronyms{display=all,pages=first}
```
and not have to put that into `\acsetup` even though it only applies to acronym listings

**Comment by cgnieder** [comment]
It's impossible because I never thought of it :)
But it is not hard to allow a setting like
```latex
\printacronyms[display=all,pages={display=all,name=true,seq/use=false}]
```
so this will be possible in the next update.
