### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by bersbersbers** [cgnieder/acro#192]
"temmplate": 
https://github.com/cgnieder/acro/blob/1e4c18bc6d8c2a33e1d251f4251d9ab7b026e7e8/doc/acro-manual.tex#L1925

**Comment by bersbersbers** [comment]
"tome kind":
https://github.com/cgnieder/acro/blob/1e4c18bc6d8c2a33e1d251f4251d9ab7b026e7e8/doc/acro-manual.tex#L2103

**Comment by cgnieder** [comment]
Thanks, fixed.
