### ISSUE TITLE
\acuse does not impact local list

### ISSUE THREAD

**Issue by bersbersbers** [cgnieder/acro#194]
I hope I haven't misunderstood `\acuse`, but it seems to me that it does not work in the context of local lists:

```
\documentclass{article}
\usepackage{acro}
\acsetup{barriers/use=true, list/local=true}
\DeclareAcronym{id}{short=short, long=long}
\begin{document}

\ac{id}
\printacronyms

\acbarrier

\acuse{id}
\printacronyms

\end{document}
```

![image](https://user-images.githubusercontent.com/12128514/101812153-4902ad00-3b1b-11eb-8b77-ae837f2768ab.png)

This can be fixed by `list/local=false`, by commenting out `\acbarrier`, or by replacing `\acuse` by `\ac` - but that does not solve the issue, obviously.

**Comment by bersbersbers** [comment]
This result indicates that `\acuse` works above the barrier although it is issued below it. Note that this example has `single=true` which the above does not.

```
\documentclass{article}
\usepackage{acro}
\acsetup{single=true, barriers/use=true, list/local=true}
\DeclareAcronym{id}{short=short, long=long}
\begin{document}

\ac{id}
\printacronyms

\acbarrier

\acuse{id}
\printacronyms

\end{document}
```

Compare the output with `\acuse{id}`
![image](https://user-images.githubusercontent.com/12128514/101812840-3341b780-3b1c-11eb-97e0-c39f4788f7c4.png)

with the output without `\acused{id}`:
![image](https://user-images.githubusercontent.com/12128514/101812884-43f22d80-3b1c-11eb-9a80-6816ea192dbf.png)

**Comment by cgnieder** [comment]
Thanks for the report. This is fixed for the next update.

**Comment by bersbersbers** [comment]
Thank you, it seems this is fixed!
