### ISSUE TITLE
 New heading templates

### ISSUE THREAD

**Issue by Alex-Muirhead** [cgnieder/acro#196]
When using the `\printacronyms` macro, there is an option for `list/heading` with possible selections of `none`, `section`, `section*`, `chapter` and `chapter*`. I would like to print acronym lists with `subsection*`, as was possible in the previous version, for the purpose of having multiple acronym lists grouped by tags. 

The current documentation has a section for "New heading templates", however no information is provided. 
How would I go about achieving this?

**Comment by cgnieder** [comment]
You would define
```latex
\NewAcroTemplate[heading]{subsection*}{\subsection*{\acrolistname}}
```
That's it. Now the template can be chosen.

**Comment by cgnieder** [comment]
Thanks for the hint to the missing section. It'll be added in the next update.

**Comment by Alex-Muirhead** [comment]
Thank you!
