### ISSUE TITLE
Tooltip not working together with links

### ISSUE THREAD

**Issue by KarlSchwenk** [cgnieder/acro#199]
## Summary
The two features 'make-links' (i.e. link to list of acronyms) and 'pdfcomments/use' (i.e. tooltip in PDF) do not work together, just separately. When attempting to use both, only links work, tooltip does not.

## Steps to Reproduce
See [this minimal example](https://gist.github.com/KarlSchwenk/677e8bff6920c6c8e402fd28eefbb2de). 
PDF viewed in Acrobat Reader to test.

## Desired Behavior
When using both features 'make-links' (i.e. link to list of acronyms) and 'pdfcomments/use' (i.e. tooltip in PDF), the resulting PDF file should show tooltip text ('pdfcomment'-value in acronym declaration) when hovering with mouse over the respective acronym. When clicking onto the acronym, the link to the list of acronyms should be followed to.

> ### Any chances to fix this?

**Comment by cgnieder** [comment]
I am not sure that it is a problem of `acro`:

```latex
\documentclass{article}
\usepackage{acro}
\usepackage{hyperref}

\acsetup{
  make-links = true,
  pdfcomments/use = true ,
  pdfcomments/cmd = [#1][#2]
}

\DeclareAcronym{ABC}{
  short = ABC ,
  long = long text ,
  pdfcomment = tooltip text
}

\begin{document}

\ac{ABC} \par
\ac{ABC}
\newpage
\printacronyms

\end{document}
```
But maybe it is. I could be a problem of nesting. As I don't have easy access to a pdfviewer which is capable of displaying the pdf comments: can you check the following example and tell me if one of the two versions is working?

```latex
\documentclass{article}
\usepackage{hyperref}
\usepackage{pdfcomment}

\begin{document}

1: \hyperlink{abc}{\pdftooltip{AAA}{aaa}} \par
2: \pdftooltip{\hyperlink{abc}{BBB}}{bbb}
\newpage
\hypertarget{abc}{here}

\end{document}
```

**Comment by KarlSchwenk** [comment]
> But maybe it is. It could be a problem of nesting. As I don't have easy access to a pdfviewer which is capable of displaying the pdf comments: can you check the following example and tell me if one of the two versions is working?

Here the results of my testing with the PDF Viewers I had available:

| PDF Viewer | Tooltip V1 | Tooltip V2 | Hyperlink V1 | Hyperlink V2 |
|---|---|---|---|---|
|**TexStudio Integrated Viewer** | ✖️  | ✖️ | ✔️ | ✔️ |
| **Acrobat Reader** | ✖️  | ✖️ | ✔️ | ✔️ |
| **Google Chrome** | ✖️  | ✖️ | ✔️ | ✔️ |
| **Microsoft Edge**  | ✔️ | ✔️ | ✖️  | ✖️|

Although the results are strange (why is tooltip working in MS Edge? 🤔), it seems that this is not an issue of nesting. 
Thus, it is most likely not an issue of _acro_, right?

**Comment by cgnieder** [comment]
Thanks for checking. Yes, it looks like nothing can be done from my side. Maybe the author of `pdfcomment` can help...

I'll close this issue here.
