### ISSUE TITLE
patch/caption can lead to non-centered single-line captions when acronyms are used more than once in that caption

### ISSUE THREAD

**Issue by bersbersbers** [cgnieder/acro#202]
I am aware this is an edge case, but ...

```latex
\documentclass{article}
\usepackage{caption}
\usepackage{acro}
\acsetup{patch/floats=false, patch/caption=true}
\DeclareAcronym{id}{short=short, long=looooooooooong}
\begin{document}
\begin{figure}
    \caption{Short captions are usually centered.}
\end{figure}
\begin{figure}
    \caption{Another one.}
\end{figure}
\begin{figure}
    \caption{This one is not: \ac{id} and \ac{id}}
\end{figure}
\end{document}

```

![image](https://user-images.githubusercontent.com/12128514/105522577-b8081f80-5cdd-11eb-94bc-d7bbd1fa79b1.png)

**Comment by bersbersbers** [comment]
Related: https://tex.stackexchange.com/a/431633/30810

**Comment by bersbersbers** [comment]
I wonder if the proper solution would involve storing (and restoring) the global `acro` state before (and after) any first-of-double evaluation. After all, you do want 
- the two evaluations to return the same result, and
- each of them to be correct in the context of the document.
So the first evaluation needs to see the global context *and be able to modify it* (since the same acronym may be reused), and the second then needs to start from the same context and again be able to modify it. I think `\acswitchoff` cannot correct deal with repeated acronym references, almost by definition.

**Comment by cgnieder** [comment]
This cannot be solved reliably for each case: if the “switchoff” case leads to a long caption and the “switchon” case to a short caption then you get a non-centered short caption.

What `\acswitchoff` does is making each `\ac...` command behave as if it was used with the optional star.

**Comment by cgnieder** [comment]
> I wonder if the proper solution would involve storing (and restoring) the global `acro` state before (and after) any first-of-double evaluation. 

This sound easier than it is: every call of a non-starred `\ac...` does three things as far as this “state” is concerned:

1. it sets the property `used` of the acronym to `true`
2. it steps an internal and acronym specific integer which counts the global usages
3. it steps a position in an integer array which corresponds to the current number of usages in between barriers

(Step two is probably redundant as the information is also contained in step three but the integer is easier to use.)

One would need to save the information about the status of all three for each possible acronym and restore after the measuring. Which also requires knowing when measuring takes place and when the real typesetting takes places. And this would be needed for the captions, the lists of things, the different tables which measure their contents. And what about this:

```latex
\documentclass{article}
\usepackage{acro,amsmath}
\DeclareAcronym{id}{short=short, long=long}

\begin{document}

\begin{align}
  \text{\ac{id} and \ac{id}}
\end{align}
\acresetall\acswitchoff
\begin{align}
  \text{\ac{id} and \ac{id}}
\end{align}

\end{document}
```

Most times the far easier solution is to tell users just to use `\acs*` (or similar) in these places.
