### ISSUE TITLE
"list-caps = true" implementation in acro 3.5

### ISSUE THREAD

**Issue by KiprasR** [cgnieder/acro#203]
The first letter capitalization option seems to be absent in acro 3.5. What is the correct way of implementing it in new version of the package?

**Comment by cgnieder** [comment]
You can use `format/list`:

```latex
\documentclass{article}
\usepackage{acro,acro-examples,mfirstuc}

\begin{document}

\acuse{ufo}

\printacronyms
\acsetup{format/list=\ecapitalisewords}
\printacronyms

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/105631679-eefe4280-5e4f-11eb-8180-18ada110a3a9.png)

**Comment by KiprasR** [comment]
This approach capitalizes all first letters of the phrase. The "list-caps = true" option used to capitalize only the first letter of the first word.

**Comment by cgnieder** [comment]
Well, yes. I just made some arbitrary example… If you open the manual to `mfirstuc` you will also find `\emakefirstuc`. Exchange `\ecapitalisewords` by `\emakefirstuc` and there you are. You could also do

```latex
\documentclass{article}
\usepackage{acro,acro-examples}

\ExplSyntaxOn
\NewDocumentCommand \upperfirst {m} { \text_titlecase:n {#1} }
\ExplSyntaxOff

\begin{document}

\acuse{ufo}

\printacronyms
\acsetup{format/list=\upperfirst}
\printacronyms

\end{document}
```

**Comment by KiprasR** [comment]
This seems to be what I was looking for. Thanks.
