### ISSUE TITLE
acro list not populated by acro defined in table

### ISSUE THREAD

**Issue by EdTrippy** [cgnieder/acro#204]
If the only instances of an acronym usage are within a table, then they do not appear when generating an acronym list.

**Comment by cgnieder** [comment]
This is a know and documented fact, cf. https://tex.stackexchange.com/questions/557187/ and #172 and section 22 (Patches) of the current manual.

**Comment by EdTrippy** [comment]
\acsetup{patch/floats=false}
Thanks. Missed that one.
