### ISSUE TITLE
Displaying in list: Long acronyms or many usages posing problems

### ISSUE THREAD

**Issue by Lozik** [cgnieder/acro#207]
When using long acronyms (or rather long 'long forms') or if a certain acronym is used on many different pages, the acronym listing behaves in a way that does not really please me. These images explain my issue better:

<img width="473" alt="Screenshot 2021-02-14 at 01 10 25" src="https://user-images.githubusercontent.com/16655002/107991805-a6155600-6fd7-11eb-98c4-3784737df6f8.png">
<img width="457" alt="Screenshot 2021-02-14 at 01 10 12" src="https://user-images.githubusercontent.com/16655002/107991819-add4fa80-6fd7-11eb-94fb-2c93d9b6329c.png">

It seems to me that there are two issues (although, correlated):
* Line breaks are not imposed if the long form is too long or if the acronym is used on too many pages. There should be a line break such that page numbers are still grouped on the right and the long forms all on the left.
* There is no horizontal space on the left side of the page numbers (in the worst case, as you can see in my images, the page number is directly next to the long form.

Is there any current solution? Is this a known issue that someone has solved? Or is this a fixable bug?

Thanks :)

**Comment by cgnieder** [comment]
It is not a bug. But a behavior that can be changed.

The manual of the current version of `acro` describes the option `pages/fill` as _This is the code that is placed between acronym description and actual page numbers._ It is initially set to `\acrodotfill`. The latter is described as _Creates a dotted line like those in the table of contents. If the macro `\cftdotfill` is defined it is equal to `\cftdotfill{\cftdotsep}`._

From the image you posted I assume that your version is older. In versions 3.0 up to but not including 3.3 the option was initially set to `\dotfill`. In version prior to v3.0 there was no option IIRC.

You didn't supply a minimal example but I guess that setting `\acsetup{pages/fill=\allowbreak\acrodotfill}` (or `\acsetup{pages/fill=\allowbreak\dotfill}`) should help.

It would be interesting to see if a current version of `acro` (which uses `\acrodotfill`) actually still shows the behavior.

**Comment by Lozik** [comment]
Thanks for your prompt response. You were right, I was not using the latest version, I was using 56982 (3.3). However, with the newest version, it is exactly the same. I tried your settings, but the results were absolutely the same.

So here is a 'minimal' (not) working example with its result:
```latex
\documentclass{article}

\usepackage{acro}
\usepackage[paper=a4paper, right = 2.5cm, left = 3.5cm]{geometry}

\DeclareAcronym{a}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of Hypertext aaaaa,
}
\DeclareAcronym{b}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of Hypertext aa,
}
\DeclareAcronym{c}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of Hypertext aaa,
}
\DeclareAcronym{d}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of Hypertext a,
}

\acsetup{
  pages/display = all,
}

\begin{document}
	\ac{a}
	\ac{b}
	\ac{c}
	\ac{d}
	\newpage
	a
	\newpage
	\ac{d}
	\newpage
	\printacronyms
\end{document}
```

![Screenshot 2021-02-17 at 15 16 05](https://user-images.githubusercontent.com/16655002/108216714-11276f80-7133-11eb-897c-88bef7bc2796.png)

**Comment by cgnieder** [comment]
The result looks exactly like I would expect it too look. I'm not entirely sure what you _want_ this to look like. Maybe like
 this:

![image](https://user-images.githubusercontent.com/2248538/108395568-380aa200-7216-11eb-9a63-0786547ed908.png)

Or rather like this:

![image](https://user-images.githubusercontent.com/2248538/108395655-51135300-7216-11eb-87b4-7f8b56041730.png)

The code for both is the following (just remove the `\mbox{}` to get the second outcome):

```latex
\documentclass{article}
\usepackage[paper=a4paper, right = 2.5cm, left = 3.5cm,showframe]{geometry}
\usepackage{acro}

\acsetup{
  pages/fill = \penalty-50\space\mbox{}\acrodotfill
}

\DeclareAcronym{a}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of
    Hypertext aaaaa
}
\DeclareAcronym{b}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of
    Hypertext aa
}
\DeclareAcronym{c}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of
    Hypertext aaa 
}
\DeclareAcronym{d}{
  short = BREACH,
  long = Browser Reconnaissance and Exfiltration via Adaptive Compression of
    Hypertext a 
}
\DeclareAcronym{e}{
  short = xx,
  long = short example
}

\acsetup{
  pages/display = all,
}

\begin{document}

\ac{a} \ac{b} \ac{c} \ac{d} \ac{e}

\newpage
a
\newpage
\ac{d}
\newpage
\printacronyms

\end{document}
```

**Comment by Lozik** [comment]
I have to admit that I wouldn't have expected (intuitively) the default to look like your third example. What I would have (and what I would wish my list to look like) would be your first proposition. However, depending on the long form of the acronym, this is not the result with your proposed `pages/fill` value.

I would use `\space\penalty-70\mbox{}\acrodotfill`. That way, there is always a space in front of the page number and single page numbers/orphans are prevented.

As I said, IMHO that would have been the way I expected it to work but well, the essential part is that one can change the behaviour :)

Thanks for your help!

**Comment by cgnieder** [comment]
Penalties are not an exact science usually :)

**Comment by Lozik** [comment]
Yes, I recon :P However what was very useful, was to put the space **before** the penalty so there is never a situation with `LongAcronymLongForm2` (with 2 the page number of course).
