### ISSUE TITLE
acro package: \ac command does always print long form

### ISSUE THREAD

**Issue by vincenthoecker** [cgnieder/acro#208]
When I'm using `\ac` command all over my text. But when compiling it's always the long-form. Also, the first appearance isn't long-short, it's also just long. When using `[version=2]` then everything works good in that way but there are other mistakes everywhere and it's not possible to load the list of acronyms.

I'm using Overleaf.  My current setup is:
`\acsetup{list / display = all , 
list / sort , 
list / heading = none ,
list / template = supertabular
}`

Is there anyone who can help me?

Edit: I could use \acl and \acs instead, but I want to use \ac.

**Comment by cgnieder** [comment]
Did you compile at least (!) twice? `acro` warns you in the log if it needs to be recompiled.

If that doesn't help please provide a *minimal* example with which I can reproduce the problem.

**Comment by vincenthoecker** [comment]
Yeah, I tried to compile a lot of times.

But I think I found a solution for this strange problem. When I'm declaring the acronyms BEFORE `\begin{document`} than everything works out. However this is quite strange because using `\acl` and `\acs` worked nevertheless.

So my solution is now using a seperate `acronyms.tex` file with declared acronyms and then including it via `\input`:

\usepackage{acro}
\input{ressources/acronyms}

\begin{document}

**Comment by cgnieder** [comment]
Yes. Acronyms *need* to be declared in the preamble. I need to look to be sure but I believe this is documented.

This requirement is from the very beginning. That it works in the document body with version 2 is just by chance, *not* by design.

**Comment by cgnieder** [comment]
>  I need to look to be sure but I believe this is documented.
> 
Indeed:
```latex
\section{\acro\ for the impatient}\label{sec:acro-impatient}

Acronyms are defined in the preamble
```
![image](https://user-images.githubusercontent.com/2248538/108391676-3939d000-7212-11eb-913b-06333f39ee49.png)
