### ISSUE TITLE
Provide a hook to add a period at the end of a footnoted long form of an acronym

### ISSUE THREAD

**Issue by dbitouze** [cgnieder/acro#215]
When `first-style=footnote` is used, the first occurrences of the acronyms are displayed as footnotes and are not ended by a final period, unlike the other, ordinary, footnotes, the content of which (usually sentences) being ended by periods. So, currently, if ordinary and acronyms footnotes are mixed up on a page, they look heterogeneous (as in the following MCE). Hence, it could be nice to provide a hook that let us add a period at the end of a footnoted long form of an acronym. 

```latex
\documentclass{article}
\usepackage{acro}
\acsetup{
  first-style=footnote
}
\DeclareAcronym{cd}{
  short = CD ,
  long = Compact Disc
}
\begin{document}
This \ac{cd} is great\footnote{Indeed, it is.}!
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/119402923-e7578900-bcdd-11eb-99a9-419baf4398b4.png)

**Comment by cgnieder** [comment]
You can redefine the `footnote` template to add the period:

```latex
\documentclass{article}
\usepackage{acro}
\acsetup{
  first-style=footnote
}
\DeclareAcronym{cd}{
  short = CD ,
  long = Compact Disc
}

\RenewAcroTemplate{footnote}{%
  \acrowrite{short}%
  \acroiffirstT{%
    \acfootnote{%
      \acroifT{alt}{\acrotranslate{or} \acrowrite{alt}: }%
      \acroifT{foreign}{\acrowrite{foreign}, }%
      \acrowrite{long}%
      \acrogroupcite
    .}% dot added
  }%
 }

\begin{document}

This \ac{cd} is great\footnote{Indeed, it is.}!

\end{document}
```

**Comment by dbitouze** [comment]
> You can redefine the `footnote` template to add the period:
> [...]

Thanks. That's more or less what I did for my own documents but (IMHO) this should be, if not the default, at least available thanks to a simple option.

**Comment by cgnieder** [comment]
I'm not sure I agree. At least I don't think it should be the default.
Maybe it's easier to just do
```latex
\ExplSyntaxOn
\NewDocumentCommand \acfootnote {m} { \acro_footnote:n {#1.} }
\ExplSyntaxOff
```

**Comment by dbitouze** [comment]
OK for the default. But what about an option?

**Comment by cgnieder** [comment]
I added a command `\acroendfootnote` to the `footnote` template which can be redefined but does nothing in its initial definition. It will be available in the next update.
