### ISSUE TITLE
Make `\DeclareAcronym` disabled after `\begin{document}`

### ISSUE THREAD

**Issue by dbitouze** [cgnieder/acro#218]
https://github.com/cgnieder/acro/blob/43e2f3e8d2130818d80884b21e8a0c9fdb9a8c9b/doc/acro-manual.tex#L344

This rule:

- on one hand, has very undesirable effect if not respected (only the long form is printed when the acronym is used for the first time with `\ac`),
- on the other hand, is not mandatory.
 
It may be useful to make `\DeclareAcronym` to be disabled after `\begin{document}` (just a matter of adding `\@onlypreamble\DeclareAcronym` somewhere in the code).

**Comment by Kaniee** [comment]
This is related to the discussed #208 and got already fixed. It's on master but it's not yet released.

**Comment by cgnieder** [comment]
I'll publish a new release soon.
