### ISSUE TITLE
Set bookmarks at v2.11d

### ISSUE THREAD

**Issue by DangeRS2** [cgnieder/acro#222]
I want to set the bookmarks by `pdfstring`, but the following MWE does not work at all. I just want to check whether the usage is right.

```latex
\documentclass{article}

\usepackage{hyperref}

\usepackage{acro}
\DeclareAcronym{test}{
	short = CV,
	long = computer vision,
	pdfstring = ABC}

\begin{document}

\section{\acl*{test}}

\acpdfstring{test}

\ac{test}
	
\end{document}
```

How to print `ABC` in the bookmarks?

**Comment by cgnieder** [comment]
There seems to be a bug in the latest v2; however, v2 is not updated anymore.

In v3 the replacement works as described for the _short_ form:

```latex
\documentclass{article}

\usepackage{hyperref}

\usepackage{acro}
\DeclareAcronym{test}{
  short = CV,
  long = computer vision,
  pdfstring = ABC
}

\begin{document}

\section{\acl*{test} vs. \acs*{test}}

\ac{test}
	
\end{document}
```
![grafik](https://user-images.githubusercontent.com/2248538/148068849-069c588b-d43a-4159-becd-1955c8207d4d.png)
