### ISSUE TITLE
\acsetup{list/template=table} -> no Output with \printacronyms

### ISSUE THREAD

**Issue by MadMe86** [cgnieder/acro#225]
Hey!

Like the Title says, with template=table either with
\printacronyms[template=table]
or
\acsetup{list/template=table}
i get no output.
in the code i found that tabular, "\acsetup{list/template=table}" works for me but \usepackage{array} also needs to be added.

**Comment by cgnieder** [comment]
This is an error in the manual. The template's name is `tabular` as you've discovered and not `table`. I'll fix the manual.
