### ISSUE TITLE
set pdfcomment to long

### ISSUE THREAD

**Issue by Fratorhe** [cgnieder/acro#226]
Hello, 

First, I'd like to thank you for the package, works great!

I'd like to know if there is a simple way to link the `long `comment to the `pdfcomment`, such that in the definition one does not need to define each `pdfcomment `if it is the same as the `long`.
Could this be done with an option in acsetup? 
Or maybe inserting a specific symbol in the `pdfcomment` field?

Regards, 
Francisco

**Comment by cgnieder** [comment]
You can do
```latex
\MakeAcroPropertyAlias{pdfcomment}{long}
```
