### ISSUE TITLE
Incompatible with Abstract in IEEE CompSoc Journal Style on macOS

### ISSUE THREAD

**Issue by sbondorf** [cgnieder/acro#233]
The style used for IEEE Computer Society journal articles (and potentially others) ``\documentclass[journal,compsoc]{IEEEtran}`` demands to put the abstract inside ``\IEEEtitleabstractindextext{ ... }``. On macOS (v12 with MacTeX 2021), acronyms in the abstract are all compiled to their long versions. This problem couldn't be reproduced on Linux.

**Comment by cgnieder** [comment]
I'm not sure I can help. This MWE

```latex
\documentclass[journal,compsoc]{IEEEtran}

\usepackage{acro}

\DeclareAcronym{MA}{
  short =MA,
  long = my acronym
}

\title{Title}
\author{author}

\begin{document}

\IEEEtitleabstractindextext{text \ac{MA} text}

\maketitle

text \ac{MA} text
text \ac{MA} text

\end{document}
```
gives

![image](https://user-images.githubusercontent.com/2248538/149618395-ce6cf085-01a9-4b09-a7a3-4433c865ac8f.png)

which seems to be alright actually (using an up to date TL21).

**Comment by sbondorf** [comment]
That part works, indeed. The problem appears within the abstract. Just change the example to use the same text as in the body, then all acronyms in the abstract are compiled to their long versions.

```
\IEEEtitleabstractindextext{text \ac{MA} text text \ac{MA} text}
```

Gives you on macOS:

<img width="1009" alt="Screen Shot 2022-01-15 at 12 10 42" src="https://user-images.githubusercontent.com/5295332/149619560-a5de2521-3300-4847-bdd3-eed8f084d786.png">

**Comment by cgnieder** [comment]
In the newest versions of `acro` the package patches `\maketitle` to not mark acronyms as used within `\maketitle`. Sadly I seem to have forgotten to document this properly…

It looks like you don't want this behaviour. It can be disabled but then due to the nature of `\maketitle` the acronym will not appear as _first_ appearance anywhere. So within `\maketitle` `\acf` might be needed and a reset after `\maketitle` probably as well:

```latex
\documentclass[journal,compsoc]{IEEEtran}

\usepackage{acro}

\DeclareAcronym{MA}{
  short =MA,
  long = my acronym
}

\title{Title}
\author{author}

\acsetup{patch/maketitle=false}

\begin{document}

\IEEEtitleabstractindextext{text \acf{MA} text \ac{MA} text}
\maketitle
\acresetall

text \ac{MA} text
text \ac{MA} text

\end{document}
```
