### ISSUE TITLE
\ace command for printing extra.

### ISSUE THREAD

**Issue by ratmice** [cgnieder/acro#264]
On occasion it would be nice to refer to print an acronym like `\acs{acronym}`, etc. Printing `extra` field by itself when referring to the given acronym.  I didn't see a way to do that already, but it seems likely that I missed something.

**Comment by NeverGameStar** [comment]
Try: \NewAcroCommand\ace{m}{\acrowrite{extra}}

**Comment by ratmice** [comment]
Thank you!  I'm going to go ahead and close this since it can be added without changing the package.
But feel free to reopen if it's something would be worth adding to the package itself.
